### ISSUE TITLE
lets talk

### ISSUE THREAD

**Issue by skariel** [theindiepocalypse/one_more_cool_game#7]
@theindiepocalypse show policy

**Comment by theindiepocalypse** [comment]
@skariel: no policy for this repo

**Comment by skariel** [comment]
@theindiepocalypse list owners

**Comment by theindiepocalypse** [comment]
@skariel: 

Owner | Percent
-------|---------
@theindiepocalypse|5
@skariel|95
*total* | 100.0

**Comment by skariel** [comment]
@theindiepocalypse show policy

**Comment by theindiepocalypse** [comment]
@skariel: no policy for this repo

**Comment by skariel** [comment]
@theindiepocalypse show policy

**Comment by theindiepocalypse** [comment]
@skariel: minimal ownership for manaing issues is 50
minimal ownership for changing policy is 50

**Comment by skariel** [comment]
@theindiepocalypse list owners

**Comment by theindiepocalypse** [comment]
@skariel: 

Owner | Percent
-------|---------
@theindiepocalypse|5
@skariel|95
*total* | 100.0

**Comment by skariel** [comment]
@theindiepocalypse close

**Comment by theindiepocalypse** [comment]
@skariel: Only owners with more than 50% ownership can close issues. You currently have 95%

**Comment by skariel** [comment]
@theindiepocalypse close

**Comment by skariel** [comment]
@theindiepocalypse open

**Comment by crazyduck2** [comment]
hi

@theindiepocalypse show policy

**Comment by theindiepocalypse** [comment]
@crazyduck2: minimal ownership for manaing issues is 50
minimal ownership for changing policy is 50

**Comment by crazyduck2** [comment]
@theindiepocalypse close

**Comment by theindiepocalypse** [comment]
@crazyduck2: Only owners with more than 50% ownership can close issues. You currently have no ownership at all...

**Comment by crazyduck2** [comment]
@theindiepocalypse policy

**Comment by theindiepocalypse** [comment]
@crazyduck2: such command... much help please

**Comment by crazyduck2** [comment]
@theindiepocalypse show policy

**Comment by theindiepocalypse** [comment]
@crazyduck2: minimal ownership for manaing issues is 50
minimal ownership for changing policy is 50

**Comment by crazyduck2** [comment]
@theindiepocalypse change issue policy 70.0

**Comment by theindiepocalypse** [comment]
@crazyduck2: such command... much help please

**Comment by crazyduck2** [comment]
@theindiepocalypse change policy issue 70.0

**Comment by theindiepocalypse** [comment]
@crazyduck2: Only owners with more than 50% ownership can change policy of this repo. You currently have no ownership at all...

**Comment by skariel** [comment]
@theindiepocalypse change policy issue 70.0

**Comment by theindiepocalypse** [comment]
@skariel: policy changed

**Comment by skariel** [comment]
@theindiepocalypse show policy

**Comment by theindiepocalypse** [comment]
@skariel: minimal ownership for manaing issues is 50
minimal ownership for changing policy is 50

**Comment by skariel** [comment]
@theindiepocalypse show policy

**Comment by theindiepocalypse** [comment]
@skariel: minimal ownership for manaing issues is 50
minimal ownership for changing policy is 50

**Comment by skariel** [comment]
@theindiepocalypse change policy issue 73.1

**Comment by theindiepocalypse** [comment]
@skariel: policy changed

**Comment by skariel** [comment]
@theindiepocalypse show policy

**Comment by theindiepocalypse** [comment]
@skariel: minimal ownership for manaing issues is 73
minimal ownership for changing policy is 50

**Comment by skariel** [comment]
@theindiepocalypse show policy

**Comment by theindiepocalypse** [comment]
@skariel: minimal ownership for manaing issues is 72
minimal ownership for changing policy is 50

**Comment by skariel** [comment]
@theindiepocalypse show policy

**Comment by theindiepocalypse** [comment]
@skariel: no policy for this repo

**Comment by skariel** [comment]
@theindiepocalypse show policy

**Comment by theindiepocalypse** [comment]
@skariel: no policy for this repo

**Comment by skariel** [comment]
@theindiepocalypse change policy issue 72.1

**Comment by skariel** [comment]
@theindiepocalypse show policy

**Comment by theindiepocalypse** [comment]
@skariel: no policy for this repo

**Comment by skariel** [comment]
@theindiepocalypse hi

**Comment by theindiepocalypse** [comment]
@skariel: hi!

**Comment by skariel** [comment]
@theindiepocalypse hi

**Comment by theindiepocalypse** [comment]
@skariel: hi!

**Comment by skariel** [comment]
@theindiepocalypse change policy issue 72.1

**Comment by skariel** [comment]
@theindiepocalypse show policy

**Comment by theindiepocalypse** [comment]
@skariel: no policy for this repo

**Comment by skariel** [comment]
@theindiepocalypse list owners

**Comment by theindiepocalypse** [comment]
@skariel: 

Owner | Percent
-------|---------
*total* | 100.0

**Comment by skariel** [comment]
@theindiepocalypse list owners

**Comment by theindiepocalypse** [comment]
@skariel: 

Owner | Percent
-------|---------
*total* | 100.0

**Comment by skariel** [comment]
@theindiepocalypse show policy

**Comment by theindiepocalypse** [comment]
@skariel: minimal ownership for manaing issues is 50.0000
minimal ownership for changing policy is 50.0000

**Comment by skariel** [comment]
@theindiepocalypse change policy issue 72.1

**Comment by theindiepocalypse** [comment]
@skariel: policy changed

**Comment by skariel** [comment]
@theindiepocalypse show policy

**Comment by theindiepocalypse** [comment]
@skariel: minimal ownership for manaing issues is 72.1000
minimal ownership for changing policy is 50.0000

**Comment by skariel** [comment]
@theindiepocalypse close
